# Site settings
title: Poeta Luzuriaga
email: diego@luzuriaga.com
description: > # this means to ignore newlines until "baseurl:"
  Escritos de Diego Luzuriaga. Writings by Diego Luzuriaga.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://poetaluzuriaga.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

collections:
  poesia:
    output: true

defaults:
  - scope:
      path: ""
      collection: poesia
    values:
      layout: poesia
